apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-mamad-namespace-fpm-wordpress-deployment
  name: fpm-wordpress-deployment
  namespace: mamad-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-mamad-namespace-fpm-wordpress-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-mamad-namespace-fpm-wordpress-deployment
    spec:
      affinity: {}
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_HOST
              name: wordpress-env
              optional: false
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_USER
              name: wordpress-env
              optional: false
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_PASSWORD
              name: wordpress-env
              optional: false
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_NAME
              name: wordpress-env
              optional: false
        image: index.docker.io/sultanahmad/fpm:v2
        imagePullPolicy: Always
        name: fpm-wordpress-container 
        ports:
        - containerPort: 9000
          name: fpm-wp-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: vol-fpm-wordpress
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol-fpm-wordpress
        persistentVolumeClaim:
          claimName: wordpress-pvc
